//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baruk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public short PersonaID { get; set; }
        public int AdminID { get; set; }
        public string UsuarioEspecial { get; set; }
        public string PasswrdEspecial { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
