//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baruk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public short PersonaID { get; set; }
        public int NumeroCedula { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public byte GeneroID { get; set; }
        public int DistritoID { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> PagoID { get; set; }
        public Nullable<short> RutinaClienteID { get; set; }
        public Nullable<byte> TipoCliente { get; set; }
        public Nullable<int> WODID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public byte TipoPersonaID { get; set; }
        public string Email { get; set; }
        public byte[] Contrasena { get; set; }
    
        public virtual Genero Genero { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual RutinasClientesAvanzado RutinasClientesAvanzado { get; set; }
        public virtual TipoCliente TipoCliente1 { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        public virtual WOD WOD { get; set; }
    }
}
